# Generated by Django 5.2.1 on 2025-05-31 03:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='逝世日期')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入图书分类 (如: 科幻, 历史, 编程...)', max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('isbn', models.CharField(help_text='13位 <a href="https://www.isbn-international.org/content/what-isbn">ISBN号</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('summary', models.TextField(blank=True, help_text='简要描述本书内容', max_length=1000, verbose_name='摘要')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('status', models.CharField(blank=True, choices=[('a', '在馆可借'), ('r', '已预订'), ('o', '已借出'), ('c', '仅供阅览'), ('m', '维护中')], default='a', help_text='图书当前状态', max_length=1, verbose_name='状态')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author', verbose_name='作者')),
                ('genre', models.ManyToManyField(blank=True, help_text='选择本书所属分类', to='catalog.genre', verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_type', models.CharField(choices=[('s', '学生'), ('t', '教师'), ('l', '馆员')], default='s', max_length=1, verbose_name='读者类型')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号/工号')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='联系电话')),
                ('max_books', models.PositiveSmallIntegerField(default=5, verbose_name='最大可借数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '读者档案',
                'verbose_name_plural': '读者档案',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出日期')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='应还日期')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('status', models.CharField(blank=True, choices=[('o', '已借出'), ('r', '已归还'), ('o', '超期中')], default='o', help_text='当前借阅状态', max_length=1, verbose_name='借阅状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='所借图书')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.readerprofile', verbose_name='借阅人')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-loan_date'],
            },
        ),
    ]
